const informeStyles = {
  textContent: {
    display: "flex",
    justifyContent: "space-between",
  },

  uen: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: "5px",
    background: "rgb(253, 128, 2, 1)",
    borderRadius: 2,
  },
  uenInmobiliaria: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: "5px",
    background: "rgb(0, 45, 175, 1)",
    borderRadius: 2,
  },
  uenUA: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: "5px",
    background: "rgb(138, 138, 135, 1)",
    borderRadius: 2,
  },
  uenConstructora: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: "5px",
    background: "rgb(75, 134, 128, 1)",
    borderRadius: 2,
  },
  container: {
    background: "rgb(253, 128, 2, 0.35)",
    margin: "5px",
    borderRadius: 2,
  },
  containerInmobiliaria: {
    background: "rgb(0, 45, 175, 0.35)",
    margin: "5px",
    borderRadius: 2,
  },
  containerUA: {
    background: "rgb(138, 138, 135, 0.35)",
    margin: "5px",
    borderRadius: 2,
  },
  containerConstructora: {
    background: "rgb(75, 134, 128, 0.35)",
    margin: "5px",
    borderRadius: 2,
  },
  containerR: {
    background: "rgb(253, 128, 2, 0.35)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerRInmobiliaria: {
    background: "rgb(0, 45, 175, 0.35)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerRUA: {
    background: "rgb(138, 138, 135, 0.35)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerRConstructora: {
    background: "rgb(75, 134, 128, 0.35)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerSR: {
    background: "rgb(253, 128, 2, 0.30)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerSRInmobiliaria: {
    background: "rgb(0, 45, 175, 0.30)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerSRUA: {
    background: "rgb(138, 138, 135, 0.30)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerSRConstructora: {
    background: "rgb(75, 134, 128, 0.30)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerA: {
    background: "rgb(253, 128, 2, 0.25)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerAInmobiliaria: {
    background: "rgb(0, 45, 175, 0.25)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerAUA: {
    background: "rgb(138, 138, 135, 0.25)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerAConstructora: {
    background: "rgb(75, 134, 128, 0.25)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerCC: {
    background: "rgb(253, 128, 2, 0.20)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerCCInmobiliaria: {
    background: "rgb(0, 45, 175, 0.20)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerCCUA: {
    background: "rgb(138, 138, 135, 0.20)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  containerCCConstructora: {
    background: "rgb(75, 134, 128, 0.20)",
    borderRadius: 2,
    justifyContent: "space-between",
    display: "flex",
    flexDirection: "row",
  },
  titleZ: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: "5px",
    borderRadius: 2,
    background: "rgb(253, 128, 2, 0.50)",
  },
  titleZInmobiliaria: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: "5px",
    borderRadius: 2,
    background: "rgb(0, 45, 175, 0.50)",
  },
  titleZUA: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: "5px",
    borderRadius: 2,
    background: "rgb(138, 138, 135, 0.50)",
  },
  titleZConstructora: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    margin: "5px",
    borderRadius: 2,
    background: "rgb(75, 134, 128, 0.50)",
  },
  titleZu: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 2,
    background: "rgb(253, 128, 2, 0.50)",
  },
  titleZuInmobiliaria: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 2,
    background: "rgb(0, 45, 175, 0.50)",
  },
  titleZuUA: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 2,
    background: "rgb(138, 138, 135, 0.50)",
  },
  titleZuConstructora: {
    display: "flex",
    flexDirection: "row",
    justifyContent: "space-between",
    borderRadius: 2,
    background: "rgb(75, 134, 128, 0.50)",
  },
};
export default informeStyles;
